"""Speculative (assisted) decode measurement for CPU inference.

Speculative decoding runs a small *draft* model to propose tokens, then verifies
them with the *target* model in parallel, keeping only the accepted ones. The
literature reports ~1.7-2x on CPU (e.g. llama.cpp with a ~10x-smaller draft).

BUT on a plain PyTorch / transformers CPU stack there is a critical caveat that
this module exists to measure, not assume: every token still requires the target
model to stream its weights through the same memory bandwidth, AND the draft
model streams *its own* weights too. On bandwidth-bound CPU (which is exactly
what this project targets), a two-model setup can easily be SLOWER than the
target model alone. We measured exactly that on this repo's own hardware: with
SmolLM2-135M drafting for Qwen2.5-0.5B, assisted decode was **0.55x** (2.10 vs
3.80 tok/s) — i.e. slower, not faster. The literature win is engine- and
scale-dependent (draft shares the engine's optimized kernels / the same loaded
KV path); it does not transfer to a naive two-HuggingFace-model CPU setup.

So `measure_speculative` returns the honestly measured speedup and a verdict
(FASTER / SLOWER / ERROR), never a claimed number. This keeps inferlast's core
promise -- measured-not-claimed -- even for a technique that sounds like a win.
"""

from __future__ import annotations
import time
from typing import Optional

import torch
from transformers import GenerationConfig


def _seq_ids(out, return_dict):
    return out.sequences if return_dict else out


def _assisted_kwargs(tokenizer=None, assistant_tokenizer=None):
    kw = {}
    if tokenizer is not None:
        kw["tokenizer"] = tokenizer
    if assistant_tokenizer is not None:
        kw["assistant_tokenizer"] = assistant_tokenizer
    return kw


def measure_speculative(
    model,
    input_ids,
    prompt_len: int,
    assistant_model,
    n_new: int = 24,
    tokenizer=None,
    assistant_tokenizer=None,
    repeats: int = 3,
    warmup: int = 1,
    do_sample: bool = False,
) -> dict:
    """Honestly measure assisted decode vs the target model alone.

    Returns a dict with per-path best tok/s and the `speedup_x` (assisted/plain,
    <1 means assistant made it SLOWER) plus a `verdict` FASTERT/SLOWER/ERROR.
    If `n_new` could not be fully generated by both paths (e.g. different EOS),
    lengths are reported so the comparison stays honest."""
    cfg = GenerationConfig(
        do_sample=do_sample,
        pad_token_id=getattr(model.config, "pad_token_id",
                             getattr(model.config, "eos_token_id", None)),
    )

    def run_with(assistant):
        def run():
            if assistant is None:
                return model.generate(
                    input_ids=input_ids, max_new_tokens=n_new,
                    generation_config=cfg, return_dict_in_generate=True)
            return model.generate(
                input_ids=input_ids, max_new_tokens=n_new,
                generation_config=cfg, return_dict_in_generate=True,
                assistant_model=assistant,
                **_assisted_kwargs(tokenizer, assistant_tokenizer))
        # warmup
        for _ in range(warmup):
            run()
        ts = []
        lens = []
        for _ in range(repeats):
            t0 = time.perf_counter()
            out = run()
            ts.append(time.perf_counter() - t0)
            lens.append(out.sequences[0].shape[0] - prompt_len)
        best = min(ts)
        toks = max(lens)
        return best, toks, toks / best

    try:
        t_plain, n_plain, tps_plain = run_with(None)
    except Exception as exc:  # plain path should basically never fail
        return {"avail": False, "error": f"plain path failed: {exc}"}

    try:
        t_asst, n_asst, tps_asst = run_with(assistant_model)
    except Exception as exc:
        return {
            "avail": True,
            "plain_tok_s": round(tps_plain, 2),
            "error": f"assisted path failed: {exc}",
        }

    speedup = tps_asst / max(tps_plain, 1e-9)
    return {
        "avail": True,
        "plain_kv_tok_s": round(tps_plain, 2),
        "assisted_tok_s": round(tps_asst, 2),
        "speedup_x": round(speedup, 2),
        "verdict": "FASTER" if speedup >= 1.05 else ("SLOWER" if speedup <= 0.95 else "FLAT"),
        "plain_tokens": n_plain,
        "assisted_tokens": n_asst,
        "note": "assisted decode needs the target AND draft to stream weights "
                "through the same CPU bandwidth; a separate HF draft model "
                "often makes it SLOWER on bandwidth-bound CPU (measured 0.55x "
                "for SmolLM2-135M drafting Qwen2.5-0.5B).",
    }
